name: Release GitHub

on:
  workflow_run:
    workflows: ["Build Redmi 5 lineage kernel"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            This is Lineaged kernel build release artifacts.
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Lineaged kernel
          path: ${{ steps.build.outputs.outfile }}
