name: Build Redmi 5 Lineaged kernel

on:
  push:
    branches:
      - 'release/base2'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Set start time
        id: start-time
        run: |
          echo "START=$(date +'%s')" >> $GITHUB_ENV
          echo "DATE=$(date +'%F')" >> $GITHUB_ENV

      - name: Checkout kernel source
        uses: actions/checkout@v2

      - name: Checkout zipper
        uses: actions/checkout@v2
        with:
          repository: SantriKode/AnyKranul3
          path: zipper

      - name: Android kernel build
        if: ${{ success() }}
        uses: SantriKode/arm64-kernel-actions@master
        id: build
        env:
          NAME: Lineaged_kernel
        with:
          arch: arm64
          compiler: neutron-clang/binutils
          defconfig: rosy-perf_defconfig
          image: Image.gz-dtb

      - name: Save compile time
        id: save-compile-time
        run: |
          END=$(date +'%s')
          BEDA=$((END - START))
          MENIT=$((BEDA / 60))
          DETIK=$((BEDA % 60))
          echo "MENIT=$MENIT" >> $GITHUB_ENV
          echo "DETIK=$DETIK" >> $GITHUB_ENV

      - name: Release build (Telegram)
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.PRIVATE_ID }}
          token: ${{ secrets.TELEGRAM_SECRET }}
          format: html
          document: ${{ steps.build.outputs.outfile }}
          message: >
            <strong>Kernel Lineaged - Release Base 2</strong> telah dibuat pada repo ${{ github.repository }} dengan <strong>Compiler Neutron Clang</strong>
            Waktu Kompilasi':' ${{ env.MENIT }} menit dan ${{ env.DETIK }} detik
            Tanggal Kompilasi ':' ${{ env.DATE }}
            Versi Lineage ':' <b>Lineage 21 Only</b>
            Hash Commits ':' <code>${{ github.sha }}</code>
            Untuk informasi lebih bisa membuka github repository <a href="https://www.github.com/naups/xiaomi_rosy_kernel/commits/${{ github.sha }}">naups</a>.
