name: Build Redmi 5 PRIVATE Extended Kernel GOOGLE CLANG

on:
  push:
    branches:
      - 'private'

jobs:
  build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Set start time
        id: start-time
        run: |
          echo "START=$(date +'%s')" >> $GITHUB_ENV
          echo "DATE=$(date +'%F')" >> $GITHUB_ENV

      - name: Checkout kernel source
        uses: actions/checkout@v2

      - name: Checkout zipper
        uses: actions/checkout@v2
        with:
          repository: SantriKode/AnyKranul3
          path: zipper

      - name: Android kernel build
        if: ${{ success() }}
        uses: SantriKode/arm64-kernel-actions@master
        id: build
        env:
          NAME: PRIVATE_Ex_kernel
        with:
          arch: arm64
          compiler: aosp-clang/main/clang-r510928/binutils
          defconfig: rosy-perf_defconfig
          image: Image.gz-dtb

      - name: Save compile time
        id: save-compile-time
        run: |
          echo "END=$(date +'%s')" >> $GITHUB_ENV
          echo "BEDA=$(expr ${{ env.END }} - ${{ env.START }} )" >> $GITHUB_ENV
          echo "MENIT=$(expr ${{ env.BEDA }} / 60 )" >> $GITHUB_ENV
          echo "DETIK=$(expr ${{ env.BEDA }} % 60 )" >> $GITHUB_ENV

      - name: Release build (Telegram)
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.PRIVATE_ID }}
          token: ${{ secrets.TELEGRAM_SECRET }}
          format: html
          document: ${{ steps.build.outputs.outfile }}
          message: <blockquote><strong>Kernel Lineaged - PRIVATE Extended</strong> telah dibuat pada repo ${{ github.repository }} dengan <strong>Compiler AOSP Google</strong>\nNama Commits :; ${{ env.commitmsg }}\nWaktu Kompilasi :; ${{ env.MENIT }} menit dan {{ env.DETIK }} detik\nTanggal Kompilasi :; ${{ env.DATE }}\nHash Commits :; <code>${{ github.sha }}</code>\nUntuk informasi lebih bisa membuka github repository <a href="https://www.github.com/naups/xiaomi_rosy_kernel/commits/${{ github.sha }}">naups</a>.</blockquote>

